# Generated by Django 3.0.2 on 2020-05-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200426_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Имя',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Сообщение',
        ),
    ]
