# Generated by Django 3.0.2 on 2020-06-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20200525_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Сообщение',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Имя',
            new_name='Name',
        ),
    ]
